### ISSUE TITLE
redirection limit exceeded

### ISSUE THREAD

**Issue by jt1971** [guillaumezin/DomoticzControl#1]
Hi there,
Excited to try your plugin. However on 7.9.0 - 1473501469 (raspberrypi) it comes with the above error when trying to connect to the repo. Any thoughts?

**Comment by guillaumezin** [comment]
What happen if you try https://guillaumezin.github.io/DomoticzControl/repository/repo.xml instead ? (httpS at the beginning) ?

**Comment by jt1971** [comment]
Thank you for the suggestion, but the same thing happens.
I am trying to install CPAN and the IO::Socket::SSL following a previous query (http://forums.slimdevices.com/showthread.php?102750-Best-way-to-solve-quot-Redirection-Limit-Exceeded-quot-errors http://forums.slimdevices.com/showthread.php?102750-Best-way-to-solve-quot-Redirection-Limit-Exceeded-quot-errors)

Thanks.

**Comment by guillaumezin** [comment]
You're probably right, I think I installed it for another plugin, that's why I didn't see the problem, and my repo redirect on HTTPS

**Comment by guillaumezin** [comment]
I will try to find another domain for the repo, github enforces https on new project, I can't disable it

**Comment by guillaumezin** [comment]
Could you try http://domoticzcontrol.site88.net/repo.xml ?

**Comment by jt1971** [comment]
Great. That works.
Now cannot the plugin to work :(
Appears on the player menu, but when I select it no domoticz setup screen appears.

[16-09-12 23:24:33.1092] Slim::Networking::IO::Select::**ANON** (131) Error: Select task failed calling Slim::Web::HTTP::processHTTP: Can't use an undefined value as a HASH reference at /var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/DomoticzControl/Settings.pm line 54.

**Comment by guillaumezin** [comment]
It should be corrected in version 1.01, change your repo URL to http://domoticzcontrol.site88.net/repo.xml if not already done

**Comment by guillaumezin** [comment]
Repo changed to http://domoticzcontrol.e-monsite.com/medias/files/repo.xml
