### ISSUE TITLE
Port field not initialized

### ISSUE THREAD

**Issue by jchodk** [guillaumezin/DomoticzControl#2]
LMS server runing on Synology package (Last official version).  Plugin version downloaded from repo.
Plugin install went smooth, setup for Squeeze Radio also, 
Domoticz option menu displayed in Squeeze Radio, but can't connect to my Domoticz server.
In LMS, I activated Debug log for plugin, and find the issue : port (8080 in my case) was not specified in request for device list, even if it is defined in setup screen).
In browser, I try adding port number to request and  get the correct response from Domoticz server.

So a quick and ugly fix, I manually edit source code to force ':8080' in initPref, problem solved : domoticz controls appears in my Radio and I can control a domoticz switch state from alarm clock on/off status.

Another minor issue (my domoticz server isn't protected), even if I leave login/password fields empty in setup screen, my squeezebox.com credentials are used.

Very useful plugin, controling LMS from domoticz is fine, but doing the reverse is better !

**Comment by guillaumezin** [comment]
Hello,

This is strange, I use port 8080 myself and never had this issue. And credentials remain empty for me:

> [17-08-27 20:01:17.8182] Plugins::DomoticzControl::Plugin::getFromDomoticz (546) Ask devices to Domoticz: http://127.0.0.1:8080/json.htm?type=devices&filter=light&used=true

Can you send me the content of "/var/lib/squeezeboxserver/prefs/plugin/DomoticzControl.prefs"?

What is your plugin version?

**Comment by guillaumezin** [comment]
By the way, it seems that for new settings to be applied, LMS must be restarted. Maybe you were mistaken by this bug while choosing your settings.

**Comment by guillaumezin** [comment]
The version 1.0.6 now applies settings immediately, do you notice a difference or do you still need to manually edit source code?

**Comment by jchodk** [comment]
Away from home, will check as soon as I came black.

**Comment by jchodk** [comment]
I update to 1.0.6. restart LMS, restart Squeeze Radio and everything went fine with port and other setup parameters. Thanxs.
